// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woqgohrttmuapsnzpcet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvcWdvaHJ0dG11YXBzbnpwY2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjAzNzcsImV4cCI6MjA3MDYzNjM3N30.V_wCvJapkl_YPvGdofSCSM-Qsck2_mbQ30Qo60Z2PeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});